
name: Container plan
on:
  pull_request:
    paths:
      - "containers/**"
      - ".github/workflows/containers.yml"

jobs:
  containers-plan:

    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./containers/Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true
      
      - name: Upload Hadolint to github
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

      - name: format json
        run: |
          FMT=$( jq . <<< ${processs.env.HADOLINT_RESULTS} )
          echo "HADOLINT_RESULTS_FMT=$FMT" >> "$GITHUB_ENV"

      - name: Update Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`json
            ${process.env.HADOLINT_RESULTS_FMT}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })