
name: Container plan
on:
  workflow-dispatch:
  push:
    branches:
      - main
    paths:
      - "containers/**"
      - ".github/workflows/containers-apply.yml"

env: 
  AWS_REGION: ca-central-1
  REGISTRY: 066023111852.dkr.ecr.ca-central-1.amazonaws.com/superset
  GITHUB_SHA: ${{ github.sha }}

permissions:
  id-token: write
  contents: write
  
jobs:
  docker-push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@main
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
        DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Container

    # TODO: Replace with a locked down IAM roel
    - name: configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        role-to-assume: arn:aws:iam::066023111852:role/cds-superset-apply 
        role-session-name: PushContainer
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@5a88a04c91d5c6f97aae0d9be790e64d9b1d47b7 # v1.7.1 
  
    - name: Build container
      working-directory: ./
      run: |
        docker build \
        --file ./containers/Dockerfile \
        --tag $REGISTRY:$GITHUB_SHA-`date '+%Y-%m-%d'` \
        --tag $REGISTRY:latest ./containers

    - name: Push Container to Amazon ECR
      run: |
        docker push $REGISTRY:$GITHUB_SHA-`date '+%Y-%m-%d'`
        docker push $REGISTRY:latest
     
    - name: Docker generate SBOM
      uses: cds-snc/security-tools/.github/actions/generate-sbom@eecd7a02a0294b379411c126b61e5c29e253676a # v2.1.4
      with:
        docker_image: "${{ env.REGISTRY }}:latest"
        dockerfile_path: "./Dockerfile"
        sbom_name: "sre-bot"
        token: "${{ secrets.GITHUB_TOKEN }}"