name: Dependency Security Updates
on:
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:
  dependency-security-update:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, '[security]') && github.event.pull_request.user.login == 'renovate[bot]'
    steps:
      - name: Send Slack notification
        env:
          PR_URL: '${{ github.event.pull_request.html_url }}'
          PR_TITLE: '${{ github.event.pull_request.title }}'
        run: |
          curl \
            --request POST \
            --header 'Content-type: application/json' \
            --data "{
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"🔒 Security dependency PR opened for Superset:\n<${PR_URL}|${PR_TITLE}>\"
                  }
                }
              ]
            }" \
            ${{ secrets.PROD_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}
