
name: Docker Pull Request
on:
  pull_request:
    paths:
      - "version.txt"
      - "docker/**"
      - ".github/workflows/docker-pr.yml"

permissions:
  contents: read

jobs:
  docker-hadolint:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      pull-requests: write

    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Hadolint
        id: hadolint
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: ./docker/Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true
      
      - name: Upload Hadolint to github
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

  python-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint and format check
        run: |
          make lint
          make ARGS=--check fmt

  docker-build:
    
    runs-on: ubuntu-24.04-arm

    steps: 

      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 
        with:
          persist-credentials: false

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/arm64 \
            --file ./docker/Dockerfile \
            --tag ${{ github.repository }}:${{ github.sha }} \
            ./docker
