name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@136412a57a7081aa63c935a2cc2918f76c34f514 # v1.11.2
        id: sre-app-token
        with:
          app-id: ${{ secrets.SRE_BOT_RW_APP_ID }}
          private-key: ${{ secrets.SRE_BOT_RW_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          token: ${{ steps.sre-app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
