name: Test Access Denied

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read

jobs:
  test-access:
    runs-on: ubuntu-latest
    
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.32.5
          
      - name: Run access denied test
        env:
          SUPERSET_USERNAME: ${{ secrets.PROD_SUPERSET_SERVICE_USER_USERNAME }}
          SUPERSET_PASSWORD: ${{ secrets.PROD_SUPERSET_SERVICE_USER_PASSWORD }}
          SUPERSET_URL: https://superset.cds-snc.ca
          UPPTIME_HEADER: ${{ secrets.PROD_UPPTIME_STATUS_HEADER }}
        run: |
          python .github/workflows/scripts/test-access-denied.py \
            "$SUPERSET_URL" \
            "$SUPERSET_USERNAME" \
            "$SUPERSET_PASSWORD" \
            "$UPPTIME_HEADER"
