name: Terraform Drift Check Production

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # At 04:00 UTC every day

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.10.3
  TERRAGRUNT_VERSION: 0.58.3
  TF_VAR_cloudwatch_alert_slack_webhook: ${{ secrets.PROD_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}
  TF_VAR_google_oauth_client_id: ${{ secrets.PROD_GOOGLE_OAUTH_CLIENT_ID }}
  TF_VAR_google_oauth_client_secret: ${{ secrets.PROD_GOOGLE_OAUTH_CLIENT_SECRET }}
  TF_VAR_sentinel_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  TF_VAR_sentinel_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
  TF_VAR_slack_api_token: ${{ secrets.PROD_SLACK_API_TOKEN }}
  TF_VAR_smtp_password: ${{ secrets.PROD_SMTP_PASSWORD }}
  TF_VAR_smtp_user: ${{ secrets.PROD_SMTP_USER }}
  TF_VAR_superset_database_username: ${{ secrets.PROD_SUPERSET_DATABASE_USERNAME }}
  TF_VAR_superset_database_password: ${{ secrets.PROD_SUPERSET_DATABASE_PASSWORD }}
  TF_VAR_superset_secret_key: ${{ secrets.PROD_SUPERSET_SECRET_KEY }}
  TF_VAR_upptime_status_header: ${{ secrets.PROD_UPPTIME_STATUS_HEADER }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.PROD_AWS_ACCOUNT_ID }}:role/cds-superset-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Get deployed version
        run: echo "INFRASTRUCTURE_VERSION=v$(cat version.txt)" >> $GITHUB_ENV

      - name: Checkout infrastructure at deployed version
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          ref: ${{ env.INFRASTRUCTURE_VERSION }}

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@cc15ce9039f6c37c592fb9930b70466b229d2e9b # v1

      - name: Check for drift
        working-directory: ./terragrunt/env/prod
        run: |
          terragrunt run-all init
          terragrunt run-all plan -detailed-exitcode