name: Terraform Plan
on:
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf-plan.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.8.2
  TERRAGRUNT_VERSION: 0.58.3
  TF_SUMMARIZE_VERSION: 0.3.5
  TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
  TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
  TF_VAR_superset_database_username: ${{ secrets.SUPERSET_DATABASE_USERNAME }}
  TF_VAR_superset_database_password: ${{ secrets.SUPERSET_DATABASE_PASSWORD }}  
  TF_VAR_superset_secret_key: ${{ secrets.SUPERSET_SECRET_KEY }}

  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:

    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@main
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ vars.PROD_AWS_ACCOUNT_ID }}:role/cds-superset-plan 
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@4719878d72d1b0078e0bce2e7571e854e79903b8 # v3.2.2
        with:
          comment-delete: true
          comment-title: "Production"
          directory: "terragrunt"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true