name: Terraform plan
on:
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_plan.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.6.6
  TERRAGRUNT_VERSION: 0.54.5

  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::066023111852:role/cds-superset-plan 
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@v3.1.0
        with:
          comment-delete: true
          comment-title: "Production"
          directory: "terragrunt"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true