name: Terraform Static Scan

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/tf-static-scan.yml"
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/tf-static-scan.yml"

permissions:
  contents: read

jobs:
  terraform-static-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Trivy Terraform Security Scan
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # v0.31.0
        with:
          scan-type: config
          scan-ref: terragrunt/aws
          trivyignores: terragrunt/aws/.trivyignore
          exit-code: 1
          ignore-unfixed: false