name: Workflow Pull Request
on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/scripts/check-workflow-run-trigger.sh"

permissions:
  contents: read

jobs:
  workflow-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Check workflow run trigger
        run: |
          .github/workflows/scripts/check-workflow-run-trigger.sh
