name: Workflow Pull Request
on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/scripts/check-workflow-run-trigger.sh"

permissions:
  contents: read

jobs:
  workflow-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check workflow run trigger
        run: |
          .github/workflows/scripts/check-workflow-run-trigger.sh
